services:
  api_server:
    build:
      context: ../../
      dockerfile: api_server/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - localnet

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11436:11434"
    restart: unless-stopped
    networks:
      - localnet

  portal:
    build:
      context: ../../examples/portal
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../../examples/portal:/app:cached
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm","run","dev","--","--host","0.0.0.0","--port","5173"]
    restart: unless-stopped
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
