[package]
name = "low-cve-api-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
tokio = { version = "1.36.0", features = ["full"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.5.2", features = ["cors", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
futures = "0.3.30"
tokio-stream = "0.1"
uuid = { version = "1.7.0", features = ["v4", "fast-rng"] }
async-trait = "0.1.77"
dotenv = "0.15.0"
