name = "adaptive-api-rust"
account_id = "5a91e619c59af6ec7a40ffccc93f2a5c"
compatibility_date = "2026-01-18"
main = "src/worker.ts"

[[containers]]
class_name = "AdaptiveApiRust"
image = "./Dockerfile"
max_instances = 3
instance_type = "basic"

[[durable_objects.bindings]]
name = "ADAPTIVE_API_RUST"
class_name = "AdaptiveApiRust"

[[migrations]]
tag = "v1"
new_classes = ["AdaptiveApiRust"]




